smtp_email_handling_email = "email that will receive the email"
smtp_email_handling_password = "password from your google app"
smtp_email_handling_port = 587
smtp_email_handling_server = "smtp.gmail.com"
